### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by ronnyek** [radutomy/VSRemoteDebugger#10]
I saw an old issue with similar input.... I've got a ssh key without passphrase and have tested it by running `ssh <username>@host` and it logs in no problem without prompting for a password.

No matter what I put in for IP, ipv4 address, ipv6 address, actual machine host name, I always get "Cannot connect to user:host : Connection Refused".

I feel like it should work. I have dotnet all setup and vsdbg installed, but it doesnt appear that its even trying to get that far yet

**Comment by ronnyek** [comment]
As a side note, if there is a decently easy way I can test the source of this on my machine, I'd be more than happy to attempt to debug the problem and report my findings. I've just never dealt with debugging a VSIX extension before.

**Comment by radutomy** [comment]
Did you generate the ssh keys exactly like in the article in the description? There are multiple SSH encryption standards and Windows SSH is particularly fussy about these types of things.

Debugging is very simple. git clone the repo, open the .sln file in Visual Studio 2019, and press F5.

**Comment by ronnyek** [comment]
Ok, So I did that very thing... found out a few things... 
1) the rsa keys were in a format or something that Revci or whatever the library itself uses didn't like. re-generating with -t rsa and redeploying those keys to the server fixed the problem
2) File copy was failing because directories didn't exist, but weren't created for me. Creating those directories fixed the problem.

Based on these problems, I had some ideas for improvement... things I could contribute if you think they make sense.

1) Activate correct output window for different phases of publish->deploy->debug process, and log out information in those windows (to make things more obvious that things are happening and to have more verbose errors.
2) Build some very basic functionality to test directory creation, and ensure if its not created (the path set in the configuration ui) so as to be able to create those directories automatically on demand (I know mkdir is already there)
3) Redirect output for commands involved in making directories and copying files to the appropriate output pane (Build/Debug)
4) Attempt to redirect output pane from remote executable to some window locally.
