### ISSUE TITLE
Cannot Install Extension on VS 2022

### ISSUE THREAD

**Issue by FreddyS96** [radutomy/VSRemoteDebugger#17]
25.01.2022 17:30:50 - Microsoft VSIX Installer
25.01.2022 17:30:50 - -------------------------------------------
25.01.2022 17:30:50 - vsixinstaller.exe version:
25.01.2022 17:30:50 - 17.1.1035-preview2
25.01.2022 17:30:50 - -------------------------------------------
25.01.2022 17:30:50 - Command line parameters:
25.01.2022 17:30:50 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Freddy Schmidt\Downloads\VSRemoteDebugger (1).vsix
25.01.2022 17:30:50 - -------------------------------------------
25.01.2022 17:30:50 - Microsoft VSIX Installer
25.01.2022 17:30:50 - -------------------------------------------
25.01.2022 17:30:51 - Initializing Install...
25.01.2022 17:30:51 - Erweiterungsdetails...
25.01.2022 17:30:51 - 	Identifier         : VSRemoteDebugger.10d7e79a-8813-4e4b-9c53-67882de01a51
25.01.2022 17:30:51 - 	Name               : VSRemoteDebugger
25.01.2022 17:30:51 - 	Author             : Radu Tomuleasa
25.01.2022 17:30:51 - 	Version            : 1.4
25.01.2022 17:30:51 - 	Description        : Remote SSH Debugging tool for Visual Studio 2019 (ARM/Raspberry Pi compatible)
25.01.2022 17:30:51 - 	Locale             : en-US
25.01.2022 17:30:51 - 	MoreInfoURL        : 
25.01.2022 17:30:51 - 	InstalledByMSI     : False
25.01.2022 17:30:51 - 	SupportedFrameworkVersionRange : [4.5,)
25.01.2022 17:30:51 - 
25.01.2022 17:30:51 - 	SignatureState     : Unsigned
25.01.2022 17:30:51 - 	Unterstützte Produkte : 
25.01.2022 17:30:51 - 		Microsoft.VisualStudio.Community
25.01.2022 17:30:51 - 			Version : [16.0,17.0)
25.01.2022 17:30:51 - 			ProductArchitecture : x86
25.01.2022 17:30:51 - 
25.01.2022 17:30:51 - 	Verweise           : 
25.01.2022 17:30:51 - 	Voraussetzungen    : 
25.01.2022 17:30:51 - 		-------------------------------------------------------
25.01.2022 17:30:51 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
25.01.2022 17:30:51 - 		Name         : Visual Studio core editor
25.01.2022 17:30:51 - 		Version      : [16.0,17.0)
25.01.2022 17:30:51 - 
25.01.2022 17:30:51 - Signaturdetails...
25.01.2022 17:30:51 - 	Extension is not signed.
25.01.2022 17:30:51 - 
25.01.2022 17:30:51 - Er wird nach passenden Produkten gesucht...
25.01.2022 17:30:51 - Installiertes Produkt gefunden - Globaler Pfad
25.01.2022 17:30:51 - Installiertes Produkt gefunden - Visual Studio Enterprise 2022
25.01.2022 17:30:51 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   bei VSIXInstaller.App.Initialize()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

![image](https://user-images.githubusercontent.com/67339617/151018406-17bb78b5-f442-4678-8b1f-8156ac61bcfd.png)

**Comment by radutomy** [comment]
The extension hasn't been updated yet to VS2022. Wait for the update which will be released in a couple of days.
