### ISSUE TITLE
How to generate ssh key with "old" method to avoid "ssh-rsa is not supported"

### ISSUE THREAD

**Issue by W1zzardTPU** [radutomy/VSRemoteDebugger#18]
ssh-keygen -m PEM -t rsa -b 4096

Just posting here to document the solution for others, please close

**Comment by radutomy** [comment]
Thank you, will update documentation.

**Comment by W1zzardTPU** [comment]
Any idea if the SSH library is updated to support the new key format?

**Comment by radutomy** [comment]
Not yet as far as I'm aware. I'll be keeping an eye out for it when it arrives.
