### ISSUE TITLE
Can not connect to the ubuntu server(by ssh?)

### ISSUE THREAD

**Issue by Looong01** [radutomy/VSRemoteDebugger#19]
![image](https://user-images.githubusercontent.com/69568351/163681712-3072081a-e7bc-49a1-bf76-05fa6ec1d036.png)
![image](https://user-images.githubusercontent.com/69568351/163681718-b710c151-a6b7-4a00-89c3-f05f59383e70.png)

**Comment by Looong01** [comment]
I use administer authorized.
windows 11
visual sutdio 2022

**Comment by radutomy** [comment]
Have you set up the ssh connection as described in the documentation?
