### ISSUE TITLE
More detail in Documentation

### ISSUE THREAD

**Issue by akasoggybunz** [radutomy/VSRemoteDebugger#3]
I am loving this. I was doing the same thing using visual studio code, but i prefer Visual studio 2019. 
Happy you are developing this.

Can you give a little more detail in the documentation on how and where to set the ssh keys.
I have the keys generated, and I think I have them in the right location. I am still unsuccessful to connect to the pi.

Any more information would be great, thank you.

**Comment by radutomy** [comment]
Updated. I'm afraid I cannot help too much on this part, as ssh key setup is a bit beyond the scope of this extension.

**Comment by akasoggybunz** [comment]
Yeah, I used ssh-keygen to generate these keys. I will try to and regenerate the keys and report back.
