### ISSUE TITLE
VsDbg connection issue

### ISSUE THREAD

**Issue by Reveon** [radutomy/VSRemoteDebugger#4]
Hi, I just found this amazing extension but I am having some troubles with the VsDbg connection.

It works fine (build, ssh connection and file transfer to Rpi) until it tries to connect to VsDbg then I get the following error:

![VsDbg](https://user-images.githubusercontent.com/29383312/81299398-74e61d80-9076-11ea-84f7-ecb9b6fd0949.png)

followed by:

`The program '' has exited with code -1 (0xffffffff).`

Any ideas what could be wrong?

**Comment by radutomy** [comment]
You possibly have an older vsdbg version installed on your Rpi already? Try removing `.vsdbg` folder on the RPi and then updating to the latest version:

curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -r linux-arm -v latest -l ~/.vsdbg

**Comment by Reveon** [comment]
I am getting the same message. 

But I tried remote debugging on VS Code and it works when program has a full dotnet path in the launch.json file:

`"program": "/home/pi/dotnet/dotnet"`

but when I set it like this:
`"program": "dotnet"`

just like it is in here:

https://github.com/radutomy/VSRemoteDebugger/blob/28c2d78574c5e703574d4683441068cc1db6dbbb/src/LocalHost.cs#L52

it stops working and display the same "program "" does not exist" message

**Comment by radutomy** [comment]
Sounds like dotnet is not registered in the path environment in Windows i.e. when you type `dotnet` in the console it should be a valid command.

**Comment by Reveon** [comment]
Dotnet command works fine for me on windows and Rpi but I did some search and this is what did the trick:

`sudo ln -s "$HOME/dotnet/dotnet" "/usr/bin/dotnet"`

And now the extension works like a charm. Thank you
