### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by Achimobil** [radutomy/VSRemoteDebugger#5]
I have done like you wrote. I create a ssh key and put them on the right places.
When I know type in a windows console "ssh DefaultAccount@192.168.1.37" I can connect without any password. So the setup works.
When I then put these things in the setting and try to use it I git an error:
Cannot connect to  DefaultAccount@192.168.1.37

It could have someting todo with the path you have in your code:
            json.adapter = "c:\\windows\\sysnative\\openssh\\ssh.exe";

I do not have a ssh mehtod at this path
The SSH default folder is: C:\Windows\System32\OpenSSH

**Comment by radutomy** [comment]
Are you running Windows x64?

**Comment by Achimobil** [comment]
Yes I do, like 90% of all users today ;)

**Comment by radutomy** [comment]
Ok. The json adapter path is correct, it's a virtual path referenced only by native 32bit applications - it doesn't exist in your normal Windows environment.

**Comment by Achimobil** [comment]
You are right, I have a raspberry Pi.

I try to debug the problem and I found 3 things.
First is something with the SSH Key. The PrivateKeyFile Constructor tells me, that there is no keyphrase, but it is there. When I put he keyphrase in the constructor the Bash method creates a time out. The Raspberry is not able toe answer with a 5 seconds timeout I put it higher and the Bash command works,
But then the file transfer failed without any response of why.

I think for my current needs your debugger is not capable, because I have written a .net core app which creates a sort of web server on the IOT and I want to debug it on the device to test the GPIO commands, but it must be build differntly. But I will try parts of your solution to achive my goal.

**Comment by radutomy** [comment]
I hope you generated the SSH key with the method I described in the documentation - Windows SCP is very finickey about the SSH key format (i.e. if you generated the ssh key via Putty it won't be recongnised). 

Also, I find it surprising that 5 seconds is not enough time for the device to respond. Let me know if you find out the reason why, and I'll increase the timeout interval.

**Comment by Achimobil** [comment]
I found out where my problems came from.

The SSH makes problems on the test connectin because you have to generate the key wihtout a passphrase. Otherwise the connectin will always fail. You should add this to your documentation

The Timeout problem is related to the fact that I have a raspberry PI 2 with windows IOT Core. The systems needs a little bit more time to connect. In my tests 10 seconds will be enaugh for 95% of the connection tries I did. 

The File transfer fails because on my rapberry is Windows IOT Core and the default path is "/bin/cool". When using a wiindows system the path can't start tie a slash. So I put in "webApp" and the file tranfer works.

But I cant start the debugging because a Visual Studio Debugger is not available with "~/.vsdbg/vsdbg". I even cant find any debugger I I can't find a hint in google where to find this to configure this.

**Comment by radutomy** [comment]
This sounds like a windows ssh problem, and it's something that unfortunately i have no control over, but I'll add that to the documentation. Glad to know it's working.

If there is no debugger folder, try installing it manually: `curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -r linux-arm -v latest -l ~/.vsdbg`

Then you should have a folder `~/.vsdbg`

**Comment by Achimobil** [comment]
> The Timeout problem is related to the fact that I have a raspberry PI 2 with windows IOT Core

I think you have not read that. On the PI is Windows IOT Core. curl is a linux command which will not work on Windows
