### ISSUE TITLE
No files getting copied

### ISSUE THREAD

**Issue by tlemmons** [radutomy/VSRemoteDebugger#9]
When I do "start remote debugging", the project folder and debug/release sub-folders are created but no files are copied into them and no errors are shown anywhere.  How can I track down what is failing?

**Comment by tlemmons** [comment]
I found the issue.  You have full path to scp hard-coded and my machine had it at a different location.  I changed it to just scp.exe without the path and it works for me.  Just have to make sure your system path environment variable is set correctly.

Another issue was that my non-interactive mode login to remote machine had an invalid path and could not find scp on remote side.

**Comment by radutomy** [comment]
The issue with just having "scp.exe" is that it might not be registered as an environment variable on some machines, hence the hardcoded path. I'll be transitioning to this https://github.com/sshnet/SSH.NET as soon as they update it for .NET Core, which will fix your issue.

**Comment by tlemmons** [comment]
Understand, you might mention where scp has to be so others wont have the same issue.  

I have another issue.  When using the code in the debugger, it all works.  When I build it and then install it as an extension in visual studio, it fails  I get a dialog box about something went wrong and in the output console: "The program 'dotnet' has exited with code -1 (0xffffffff)."  Does not matter if debug or release version is used.  Any idea what could cause that?
